version: '3.1'

services:
  frontend:
    image: markwryan/canvass-frontend:latest
  backend:
    image: markwryan/canvass:latest
    restart: unless-stopped
    ports:
      - "8088:8080"
    depends_on:
      - db
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
    ports:
      - "3306:3306"
    volumes:
      - ./database/init:/docker-entrypoint-initdb.d
