version: '3.1'

services:
  canvass-frontend:
    image: markwryan/canvass-frontend:latest
    restart: unless-stopped
    ports:
      - "8089:80"
    links:
      - canvass-backend
    volumes:
      - ./nginx:/etc/nginx/conf.d/
    depends_on:
      - canvass-backend
  canvass-backend:
    image: markwryan/canvass:latest
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mariadb://maria-db:3306/canvass"
      SPRING_DATASOURCE_PASSWORD: "example"
    ports:
      - "8088:8080"
    depends_on:
      - maria-db
  maria-db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: "example"
    ports:
      - "3306:3306"
    volumes:
      - ./database/init:/docker-entrypoint-initdb.d
